export const ELEMENTS = {

    loginWindow: ".bem-vindo",
    // REGISTER
    inputInLoginForRegister: "fieldset > div > #id_email",
    buttonInLoginForRegister: "fieldset > div > .botao",
    emailInRegister: "#id_email",
    confirmEmailInRegister: "#id_confirmacao_email",
    passwordInRegister: "#id_senha",
    confirmPasswordInRegister: "#id_confirmacao_senha",
    typePersonInRegister: "#id_tipo",
    nameInRegister: "#id_nome",
    CPFInRegister: "#id_cpf",
    cellphoneInRegister: "#id_telefone_celular",
    telInRegister: "#id_telefone_principal",
    genderInRegister: "#id_sexo",
    birthDayInRegister: "#id_data_nascimento",
    cepInRegister: "#id_cep",
    addressInRegister: "#id_endereco",
    numberAddressInRegister: "#id_numero",
    complementAddressInRegister: "#id_complemento",
    referenceAddressInRegister: "#id_referencia",
    districtAddressInRegister: "#id_bairro",
    cityInRegister: "#id_cidade",
    stateInRegister: "#id_estado",
    buttonConfirmRegister: ".span3 > .principal",
    alertError: ".alert-danger",

    // LOGIN
    inputEmailInLogin: ".controls > #id_email",
    inputPasswordInLogin: "#id_senha",
    continueButtonInLogin: ".controls > .botao",

    //CART
    productPrice: ".hidden-phone > .preco-produto > div > .preco-promocional",
    quantityInput: ".input-mini",
    minusQuantity: ".icon-minus",
    plusQuantity: ".icon-plus",
    deleteProduct: ".excluir",
    inputFreight: "#calcularFrete",
    buttonFreight: "#formCalcularFrete > .control-group > .controls > .input-append > .btn",
    deliveryType: ".radio > input",
    valueDeliveryType: ".radio > .cor-principal",
    inputCoupon: "#usarCupom",
    buttonCoupon: ".input-append .btn",
    percentageCoupon: "#cupom_desconto",
    labelFreeShippingCoupon: ".cupom-valor > .cor-secundaria",
    labelCoupon: ".cupom-codigo",
    labelSubTotal: ".subtotal .titulo",
    labelTotal: ".total > .titulo",
    buttonFinalizeOrder: ".span12 > .principal",

    // CHECKOUT
    radioAddressCheckout: "#idEnderecoPrincipal1",
    radioPickUpCheckout: "#formaEnvio12015-retirar_pessoalmente",
    radioPACCheckout: "#formaEnvio2-pac",
    radioSedexCheckout: "#formaEnvio1-sedex",
    radioCreditCard: "#radio-cartao",
    radioMercadoPago: "#radio-mercadopagov1-18",
    radioBillet: "#radio-mercadopagov1-520160",
    labelQtyProductCheckout: ".conteiner-qtd > div",
    labelUnitPriceCheckout: ".preco-produto > .preco-promocional",
    labelSubTotalCheckout: ".subtotal > .titulo",
    labelShippingTaxCheckout: ".frete-preco > .titulo",
    labelDiscountsCheckout: ".desconto-preco > .titulo",
    labelDiscountsCouponCheckout: "#cupomResultado > .titulo",
    labelFreeShippingCouponCheckout: "#cupomResultado > strong",
    labelTotalCheckout: ".total > .titulo",
    buttonFinalizeOrderCheckout: "#finalizarCompra",

    //POST CHECKOUT
    labelMessageBilletPostCheckout: "#mensagemBoleto > h3",
    buttonPrintOutBilletPostCheckout: "#imprimirBoleto",
    labelWaitPaymentBilletPostCheckout: ".span4 .caixa-info span b.cor-principal",
    labelDeadlinePostCheckout: 'strong > .cor-principal',
    labelOrderNumberPostCheckout: ".span4 .caixa-info span b.cor-principal",
    iframeBilletPostCheckout: "#iframe-boleto",
    imgPostCheckout: ".caixa-info img",
    boxPersonalInfoPostCheckout: ".span12 > fieldset > .caixa-info",
    labelQuantityProductPostCheckout: "tbody tr:first td div",
    labelUnitPricePostCheckout: ".preco-promocional",
    labelSubTotalPostCheckout: ".subtotal > .titulo",
    labelShippingTaxPostCheckout: ".frete-preco > .titulo",
    labelDiscountsPostCheckout: ".desconto-preco > .titulo",
    labelCouponNamePostCheckout: ".text-right > strong",
    labelTotalPostCheckout: ".total > .titulo"
}